server: 
    port: 8080
    servlet:
        context-path: /
    ssl:
        key-store: classpath:server.p12
        key-store-password: Pk-87654321
        keyStoreType: PKCS12
        keyAlias: 1

# link to db driver
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://avocadues.cnsvk36zdydy.us-east-2.rds.amazonaws.com:3306/Avocadues?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: admin
    password: Pk-87654321
    type: com.alibaba.druid.pool.DruidDataSource
  # mvc:
  #   # prefix and sufix for view layer
  #   view:
  #     prefix: /WEB-INF/
  #     suffix: .jsp
  # main:
  #   web-application-type: none

# mybatis config
mybatis: 
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.avocadues.todolist.entity
    configuration:
        map-underscore-to-camel-case: true

# check for sql 
logging:
  level: 
    com.avocadues.todolist.mapper: DEBUG 